name: "Podcast Generator"
author: "Prayush Adhikari"
description: "Generates a feed for a podcast from a YAML file"
runs:
  using: "docker"
  image: "Dockerfile" 
branding: 
  icon: "git-branch"  # Check GitHub's available icons for correct names
  color: "red"  # Choose a valid color for your branding
inputs:
  email:
    description: "The committer's email address"
    required: true
    default: "${{ github.actor }}@localhost"
  name:
    description: "The committer's name"
    required: true
    default: "${{ github.actor }}"
